drop table if exists comments;
drop table if exists booking;
drop table if exists item;
drop table if exists users;

create table if not exists users
(
    id    BIGINT generated by default as identity not null,
    name  CHARACTER VARYING                       not null,
    email CHARACTER VARYING(512)                  not null,
    constraint USERS_PK
        primary key (id),
    unique (email)
);


create table if not exists item
(
    id           BIGINT generated by default as identity not null,
    name         CHARACTER VARYING(500)                  not null,
    description  CHARACTER VARYING(500),
    is_available BOOLEAN                                 not null,
    owner        BIGINT,
    constraint ITEM_PK
        primary key (id),
    constraint ITEM_USERS_ID_FK
        foreign key (owner) references users
);


create table if not exists booking
(
    id         BIGINT generated by default as identity not null,
    start_time timestamp without time zone,
    end_time   timestamp without time zone,
    item       BIGINT,
    booker     BIGINT,
    status     CHARACTER VARYING(500)                  not null,
    constraint BOOKINGS_PK
        primary key (id),
    constraint BOOKINGS_USERS_ID_FK
        foreign key (booker) references users,
    constraint BOOKING_ITEM_ID_FK
        foreign key (item) references item
);

create table if not exists comments
(
    id          BIGINT generated by default as identity not null,
    text        CHARACTER VARYING(500),
    item_id     BIGINT                                  not null,
    user_id     BIGINT                                  not null,
    create_time TIMESTAMP without time zone,
    constraint COMMENTS_PK
        primary key (id),
    constraint COMMENTS_ITEM_ID_FK
        foreign key (item_id) references item,
    constraint COMMENTS_USERS_ID_FK
        foreign key (user_id) references users
);

--
-- delete
-- from comments;
-- alter table comments
--     alter column
--         id restart with 1;
--
-- delete
-- from booking;
-- alter table booking
--     alter column
--         id restart with 1;
--
-- delete
-- from item;
-- alter table item
--     alter column
--         id restart with 1;
--
-- delete
-- from users;
-- alter table users
--     alter column
--         id restart with 1;


-- -- drop type booking_status cascade;
-- -- create type booking_status as ENUM ('WAITING','APPROVED', 'REJECTED', 'CANCELED');




